// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCpF2SXTnJOE_-NrB24vC9eXrDYJSyhKs',
    appId: '1:709651321933:web:52a4c5766139566334f804',
    messagingSenderId: '709651321933',
    projectId: 'chatapp-c19bd',
    authDomain: 'chatapp-c19bd.firebaseapp.com',
    storageBucket: 'chatapp-c19bd.firebasestorage.app',
    measurementId: 'G-NB3GJJHBHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaaVlFYRIGRnx7AMd_RVSeYOBGi8wt_pg',
    appId: '1:709651321933:android:322b009f7ae1d3e734f804',
    messagingSenderId: '709651321933',
    projectId: 'chatapp-c19bd',
    storageBucket: 'chatapp-c19bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjv2R7XyvFVrnGcMVnvXX5GGX-vUkVF2U',
    appId: '1:709651321933:ios:24ab990951db7a9334f804',
    messagingSenderId: '709651321933',
    projectId: 'chatapp-c19bd',
    storageBucket: 'chatapp-c19bd.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjv2R7XyvFVrnGcMVnvXX5GGX-vUkVF2U',
    appId: '1:709651321933:ios:24ab990951db7a9334f804',
    messagingSenderId: '709651321933',
    projectId: 'chatapp-c19bd',
    storageBucket: 'chatapp-c19bd.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCpF2SXTnJOE_-NrB24vC9eXrDYJSyhKs',
    appId: '1:709651321933:web:fd7dd5e87d7cfeb834f804',
    messagingSenderId: '709651321933',
    projectId: 'chatapp-c19bd',
    authDomain: 'chatapp-c19bd.firebaseapp.com',
    storageBucket: 'chatapp-c19bd.firebasestorage.app',
    measurementId: 'G-1E0RQWTV15',
  );
}
